In [2]:
class Perro:
    def __init__(self, nombre="Bobby"):
        self.nombre = nombre
    @property
    def nombre(self):
        return self.__nombre
    @nombre.setter
    def nombre(self, val):
        self.__nombre = val
        

In [3]:
mi_perro = Perro('sac') 

In [4]:
mi_perro.nombre

'sac'

In [5]:
dir(mi_perro)

['_Perro__nombre',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'nombre']

In [78]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [82]:
a = np.append(a,6)
print(a)

[1 2 3 4 5 6 6 6]


In [26]:
class Alumno: 
    
    def __init__(self,nombre='',apellido='',codigo=''):
        self.nombre = nombre
        self.apellido = apellido
        self.codigo = codigo
        self.matricula = False
    @property
    def nombre(self):
        return self.__nombre
    @property
    def apellido(self):
        return self.__apellido
    @property
    def codigo(self):
        return self.__codigo
    
    @nombre.setter
    def nombre(self,val):
        if isinstance(val,str):
            self.__nombre = val
        else:
            raise TypeError("El campo 'nombre' debe ser tipo 'str'")
    @nombre.setter
    def apellido(self,val):
        if isinstance(val,str):
            self.__apellido = val
        else:
            raise TypeError("El campo 'apellido' debe ser tipo 'str'")
    @nombre.setter
    def codigo(self,val):
        if isinstance(val,str):
            self.__codigo = val
        else:
            raise TypeError("El campo 'codigo' debe ser tipo 'str'")
    
    def esta_matriculado(self):
        return self.matricula
    
    def __repr__(self):
        return f"Alumno(nombre={self.nombre}, apellido={self.apellido}, codigo={self.codigo})"
    
            
            
       

In [30]:
alumno1 = Alumno('Elvio', 'Lado', 'u201416172')
print(alumno1)
print(alumno1.esta_matriculado())
print(alumno1.matricula)
alumno1.matricula = True
print(alumno1.esta_matriculado())
print(alumno1.matricula)


Alumno(nombre=Elvio, apellido=Elvio, codigo=Elvio)
False
False
True
True


In [38]:
# HERENCIA
class Delegado(Alumno):
    def __init__(self,nombre, apellido, codigo, curso):
        super().__init__(nombre, apellido, codigo)
        self.curso = curso
        
    def __repr__(self):
        return f"Delegado(nombre={self.nombre}, apellido={self.apellido}, codigo={self.codigo}, curso={self.curso})"
                


In [39]:
delegada = Delegado('Dina','Mita','u201416253','Programación')
print(delegada)
print(delegada.esta_matriculado())
print(delegada.matricula)
delegada.matricula = True
print(delegada.esta_matriculado())

Delegado(nombre=Dina, apellido=Dina, codigo=Dina, curso=Programación)
False
False
True


In [44]:
# classmethod
class Alumno:
    matriculado = False
    
    def __init__(self, nombre='',apellido='', codigo=''):
        self.nombre = nombre
        self.apellido = apellido
        self.codigo = codigo
        
    def esta_matriculado(self):
        return matriculado # return cls.matriculado tambien puede ser
    
    def __repr__(self):
        return f"Alumno(nombre={self.nombre}, apellido={self.apellido}, codigo={self.codigo})"
    
        
    

In [51]:
alumno1= Alumno('Elvio','Lado','u201417164')
alumno2=Alumno('Elsa','Pallo','u201618362')
print(alumno1)
print(alumno1.matriculado)
print(alumno2)
print(alumno2.matriculado)
Alumno.matriculado = True # A la clase completa la matriculo
print(alumno1.matriculado)
print(alumno2.matriculado)



Alumno(nombre=Elvio, apellido=Lado, codigo=u201417164)
True
Alumno(nombre=Elsa, apellido=Pallo, codigo=u201618362)
True
True
True


In [74]:
class Alumno:
    matriculado = False
    
    def __init__(self, nombre='', apellido='', codigo=''):
        self.nombre = nombre
        self.apellido = apellido
        self.codigo = codigo
    
    def esta_matriculado(self):
        return matriculado
    
    @classmethod
    def from_string(cls, string):
        nombre, apellido, codigo = string.split()
        return cls(nombre, apellido, codigo) # cls: Equivalente a Alumno(nombre, apellido, codigo)
    
    def __repr__(self):
        return f"Alumno(nombre={self.nombre}, apellido={self.apellido}, codigo={self.codigo})"
    
    
        
    

In [79]:
alumno_str = "Elvio Lado u201317234"
alumno1 = Alumno.from_string(alumno_str)
print(alumno1)

Alumno(nombre=Elvio, apellido=Lado, codigo=u201317234)


In [88]:
mat = np.matrix("[[1,2]; [3,4]]")
mat1 = np.matrix("1, 2; 3, 4")
print(mat)
print(mat1)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [90]:
# NAMEDTUPLES
vel_pendulo = 15.4
peso_pendulo = 50
long_cuerd_pend = 10
#Esto no me conviene
#Entonces
pendulo = pendulo(masa, long, osc1, .....)
pendulo.osc
pendulo.masa

pendulo.oscila()



SyntaxError: invalid syntax (<ipython-input-90-e540395ec655>, line 7)

In [98]:
from collections import namedtuple
# namedtuple(clase, propiedades)
Alum = namedtuple('Alum', ['nombre','apellido','codigo','matriculado']) # Tiene su propio __repr__

In [100]:
alum1 = Alum('Elvio','Lado','u201416834', False)
print(alum1.nombre)
print(alum1)

Elvio
Alum(nombre='Elvio', apellido='Lado', codigo='u201416834', matriculado=False)


In [157]:
# Metodos magicos
class Resistencia:
    def __init__(self, val=1000):
        self.val = val
    
    def __add__(self, other):
        return Resistencia(self.val + other.val)
    def __floordiv__(self,other): # Division entera, entra aquí cuando ejecuten a // b
        return 1 / (1/self.val + 1/other.val)
    def __repr__(self):
        return f"Resistencia(val={self.val})"
    



In [162]:
R1 = Resistencia(1000)
R2 = Resistencia(1000)
# En ves de hacer R1.en_serie(R2), se hace
#resul = R1 + R2
#print(resul)
print(R1 + R2+R2+R2)
print(R1 // R2)

Resistencia(val=4000)
500.0


In [163]:
print(8/3)
print(8//3)


2.6666666666666665
2


In [190]:
a = ['hola','b','c']
len(a)
b=[[2,3],[4,5],[2,5],[4,8],[3,9]]

In [198]:
k =b[::2] #Imprime desde el inicio luego de 2 en 2
k1 = b[3::] # Imprime desde la posicion 2 hasta el final
print(k)
print(k1)

[[2, 3], [2, 5], [3, 9]]
[[4, 8], [3, 9]]


In [1]:
from random import choice
a=[1,2,3,4]
b=choice(a)
print(b)

1


In [3]:
# EJEMPLO sorten con KEY
a = [
      [1,7,'z'],
      [3,2,'x'],
      [1,8,'r'],
      [2,2,'s'],
      [1,9,'b'],
      [2,2,'a']
    ]
for a in sorted(a, key=lambda x:x[2]):
    print(a) 


[2, 2, 'a']
[1, 9, 'b']
[1, 8, 'r']
[2, 2, 's']
[3, 2, 'x']
[1, 7, 'z']
